details:
  namespace: student102-bookinfo-dev
  image: ghcr.io/porplatakkom/details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-details
  port: 8080
  healthCheckPath: "/health"

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: final.porplatakkom.com
  path: "/student102/details(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
